# Package Management
package_manager: yay
update_cache: yes

# Core System Packages (pacman)
core_packages:
  - git
  - curl
  - stow
  - unzip
  - wget
  - base-devel
  - cargo

# CLI Tools (pacman)
cli_packages:
  - eza
  - zoxide
  - bat
  - fzf
  - htop
  - btop
  - cava
  - cmatrix
  - cbonsai
  - pipe.sh
  - sl
  - tty-clock
  - yazi

# CLI Tools (AUR - yay)
cli_aur_packages:
  - fastfetch
  - ttyper

# Development Tools (pacman)
dev_packages:
  - clang
  - go
  - tmux
  - vim
  - nodejs
  - npm
  - neovim
  - docker
  - github-cli

# Development Tools (AUR - yay)
dev_aur_packages:
  - yarn
  - lazygit
  - lazydocker

# Shell & Terminal (pacman)
shell_packages:
  - zsh
  - xsel
  - wl-clipboard

# Shell & Terminal (AUR - yay)
shell_aur_packages:
  - oh-my-zsh-git
  - zsh-autosuggestions
  - zsh-syntax-highlighting
  - starship

# Desktop Environment (pacman)
gnome_packages:
  - gnome-tweaks
  - gnome-shell-extensions
  - gnome-browser-connector

# GNOME Extensions (AUR - yay)
gnome_extensions:
  - gnome-shell-extension-spacebar-git
  - gnome-shell-extension-dash-to-dock

# Window Managers (pacman)
wm_packages:
  - i3lock-color
  - picom
  - polybar
  - rofi
  - autotile
  - feh
  - scrot
  - sway
  - waybar
  - swaylock
  - swaybg
  - wlogout
  - grimshot

# Window Managers (AUR - yay)
wm_aur_packages:
  - waypaper

# Applications (pacman)
applications_pacman:
  - discord
  - obs-studio
  - vlc
  - libreoffice-still

# Applications (AUR - yay)
applications:
  - code
  - cursor-bin
  - brave-bin
  - postman-bin
  - mongodb-compass-bin
  - spotify-cli
  - spicetify
  - obsidian

# Fonts (pacman)
fonts:
  - nerd-fonts-jetbrains-mono

# User Configuration
ansible_user: "{{ lookup('env', 'ANSIBLE_USER') | default('ssk') }}"
ansible_ssh_private_key_file: "{{ lookup('env', 'ANSIBLE_SSH_KEY') | default('~/.ssh/id_rsa') }}"
