---
# Install shell packages using the common package manager role
- name: Install shell packages
  include_role:
    name: package-manager
  vars:
    package_list: "{{ shell_packages }}"
    snap_package_list: "{{ shell_packages_snap | default([]) }}"
    flatpak_package_list: "{{ shell_packages_flatpak | default([]) }}"
    cargo_package_list: "{{ shell_packages_cargo | default([]) }}"

- name: Set Zsh as default shell
  user:
    name: "{{ ansible_user }}"
    shell: /bin/zsh

# Install fonts using the common package manager role
- name: Install fonts
  include_role:
    name: package-manager
  vars:
    package_list: "{{ fonts }}"

- name: Refresh font cache
  shell: fc-cache -f -v
  args:
    executable: /bin/bash

- name: Install Oh My Zsh for user
  shell: |
    RUNZSH=no CHSH=no sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  args:
    executable: /bin/bash
    creates: "/home/{{ ansible_user }}/.oh-my-zsh"
  become_user: "{{ ansible_user }}"

- name: Set custom zsh plugin path
  set_fact:
    zsh_custom: "/home/{{ ansible_user }}/.oh-my-zsh/custom"

- name: Install zsh-autosuggestions
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions.git
    dest: "{{ zsh_custom }}/plugins/zsh-autosuggestions"
  become_user: "{{ ansible_user }}"

- name: Install zsh-syntax-highlighting
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: "{{ zsh_custom }}/plugins/zsh-syntax-highlighting"
  become_user: "{{ ansible_user }}"
