---
- name: Install shell packages
  pacman:
    name: "{{ shell_packages }}"
    state: present
    update_cache: yes

- name: Set Zsh as default shell
  user:
    name: "{{ ansible_user }}"
    shell: /bin/zsh

- name: Set variables
  set_fact:
    user: "{{ ansible_user }}"
    zsh_custom: "/home/{{ ansible_user }}/.oh-my-zsh/custom"

- name: Install Oh My Zsh for user
  shell: |
    RUNZSH=no CHSH=no sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  args:
    executable: /bin/bash
    creates: "/home/{{ ansible_user }}/.oh-my-zsh"
  become_user: "{{ user }}"

- name: Install zsh-autosuggestions
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions.git
    dest: "{{ zsh_custom }}/plugins/zsh-autosuggestions"
  become_user: "{{ user }}"

- name: Install zsh-syntax-highlighting
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: "{{ zsh_custom }}/plugins/zsh-syntax-highlighting"
  become_user: "{{ user }}"

- name: Install Starship
  shell: |
    curl -fsSL https://starship.rs/install.sh | sh -s -- -y
  args:
    creates: /usr/local/bin/starship
  become_user: "{{ user }}"

- name: Stow dotfiles
  shell: |
    cd /home/{{ ansible_user }}/dotfiles && stow .
  become_user: "{{ user }}"
