- name: Install Zsh
  package:
    name: zsh
    state: present

- name: Set Zsh as default shell
  user:
    name: "{{ ansible_user }}"
    shell: /bin/zsh

- name: Install Oh My Zsh non-interactively
  shell: |
    RUNZSH=no CHSH=no sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  args:
    executable: /bin/bash
    creates: "/root/.oh-my-zsh"

- name: Set variables
  set_fact:
    user: "{{ ansible_user }}"
    zsh_custom: "/home/{{ ansible_user }}/.oh-my-zsh/custom"

- name: Install zsh-autosuggestions
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions.git
    dest: "{{ zsh_custom }}/plugins/zsh-autosuggestions"
  become_user: "{{ user }}"

- name: Install zsh-syntax-highlighting
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: "{{ zsh_custom }}/plugins/zsh-syntax-highlighting"
  become_user: "{{ user }}"

- name: Install JetBrainsMono Nerd Font
  shell: |
    wget -qO JetBrainsMono.zip https://github.com/ryanoasis/nerd-fonts/releases/download/v3.1.1/JetBrainsMono.zip
    unzip -q JetBrainsMono.zip -d /usr/local/share/fonts/JetBrainsMono
    fc-cache -f -v
    rm -f JetBrainsMono.zip
  args:
    chdir: /tmp
    creates: /usr/local/share/fonts/JetBrainsMono

- name: Install Starship
  shell: |
    curl -fsSL https://starship.rs/install.sh | sh -s -- -y
  args:
    creates: /usr/local/bin/starship

- name: Install xsel and wl-clipboard
  package:
    name:
      - xsel
      - wl-clipboard
    state: present
