# YAML Lint Configuration
extends: default

rules:
  # Line length
  line-length:
    max: 120
    level: warning

  # Comments
  comments:
    min-spaces-from-content: 1

  # Indentation
  indentation:
    spaces: 2
    indent-sequences: true

  # Document separators
  document-start:
    present: true

  # Brackets
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 1

  # Braces
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1

ignore: |
  .github/
  .git/
  *.md