---
- hosts: local
  become: true

  pre_tasks:
    - name: Update APT repo cache
      tags: always
      apt:
        update_cache: yes
      changed_when: false

    - name: Install core tools and build essentials
      package:
        name:
          - git
          - curl
          - stow
          - unzip
          - wget
          - build-essential
          - cargo
        state: present

  roles:
    - ssh
    - common
    - shell
    - cli
    - dev
    - gnome
    - wm
    - applications
