---
- hosts: local
  become: true
  environment:
    LANG: en_US.UTF-8
    LC_ALL: en_US.UTF-8
  vars_files:
    - group_vars/all.yml

  pre_tasks:
    - name: Update package cache
      tags: always
      shell: yay -Sy
      changed_when: false

    - name: Install core packages
      shell: yay -S {{ core_packages | join(' ') }} --noconfirm
      args:
        executable: /bin/bash

  roles:
    - ssh
    - common
    - shell
    - cli
    - dev
    - gnome
    - wm
    - applications
