---
- hosts: local
  become: true
  vars_files:
    - group_vars/all.yml

  pre_tasks:
    - name: Update package cache
      tags: always
      yay:
        update_cache: yes
      changed_when: false

    - name: Install core packages
      yay:
        name: "{{ core_packages }}"
        state: present

  # roles:
  #   - ssh
  # - common
  # - shell
  # - cli
  # - dev
  # - gnome
  # - wm
  # - applications
