---
- hosts: local
  become: true
  vars_files:
    - group_vars/all.yml

  pre_tasks:
    - name: Update package cache
      tags: always
      pacman:
        update_cache: yes
      changed_when: false

    - name: Install yay if not present
      block:
        - name: Install base-devel and git
          pacman:
            name:
              - base-devel
              - git
            state: present

        - name: Clone yay repository
          git:
            repo: https://aur.archlinux.org/yay.git
            dest: /tmp/yay
            force: yes

        - name: Build and install yay
          shell: |
            cd /tmp/yay
            makepkg -si --noconfirm
          args:
            creates: /usr/bin/yay

    - name: Install core packages
      pacman:
        name: "{{ core_packages }}"
        state: present

  roles:
    - ssh
    - common
    - shell
    - cli
    - dev
    - gnome
    - wm
    - applications
