---
- hosts: local
  become: true
  vars_files:
    - group_vars/all.yml

  pre_tasks:
    - name: Update package cache
      tags: always
      pacman:
        update_cache: yes
      changed_when: false

    - name: Install core packages
      pacman:
        name: "{{ core_packages }}"
        state: present

  roles:
    - role: jahrik.yay
      vars:
        yay_user: "{{ ansible_user }}"
    # - ssh
    # - common
    # - shell
    # - cli
    # - dev
    # - gnome
    # - wm
    # - applications
