---
- hosts: local
  pre_tasks:
    - name: Gather system facts
      setup:
      tags: always

  roles:
    - distro-setup  # Detect distribution and setup package managers
    - role: package-manager
      vars:
        package_list: "{{ core_packages }}"
      tags: core
    - common
    - shell
    - cli
    - dev
    - applications
