---
- name: Install applications via yay
  shell: |
    yay -S --noconfirm {{ applications | join(' ') }}
  args:
    creates: /usr/bin/code
  become: true

- name: Load Spicetify
  shell: |
    spicetify backup
    spicetify apply
  args:
    creates: ~/.config/spicetify/config.ini
  become_user: "{{ ansible_user }}"
