---
- name: Install applications via yay
  become: true
  shell: |
    yay -S --noconfirm --skipchecks {{ applications | join(' ') }}
  args:
    executable: /bin/bash
    creates: /usr/bin/code
  become_user: "{{ ansible_user }}"
