---
- name: Install applications via yay
  become: true
  shell: |
    yay -S --noconfirm --skipchecks {{ applications | join(' ') }}
  args:
    executable: /bin/bash
    creates: /usr/bin/code
  become_user: "{{ ansible_user }}"

- name: Ensure spicetify config directory exists
  file:
    path: "/home/{{ ansible_user }}/.config/spicetify"
    state: directory
    mode: "0755"
  become_user: "{{ ansible_user }}"

- name: Set prefs_path in spicetify config-xpui.ini
  lineinfile:
    path: "/home/{{ ansible_user }}/.config/spicetify/config-xpui.ini"
    line: "prefs_path = /home/{{ ansible_user }}/.config/spotify/prefs"
    create: yes
  become_user: "{{ ansible_user }}"
  when: spicetify_check.stat.exists

- name: Load Spicetify
  shell: |
    spicetify backup
    spicetify apply
  args:
    executable: /bin/bash
    creates: "/home/{{ ansible_user }}/.config/spicetify/config.ini"
  become_user: "{{ ansible_user }}"
  when: spicetify_check.stat.exists
