- name: Install GNOME tools
  package:
    name:
      - gnome-tweaks
      - gnome-shell-extensions
      - gnome-browser-connector
    state: present
  become: true

- name: Set workspace switching shortcuts
  dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
  loop:
    # Super + / to switch to next workspace (right)
    - key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-right"
      value: "['<Super>slash']"

    # Super + . to switch to previous workspace (left)
    - key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-left"
      value: "['<Super>period']"

    # Super + Shift + 1/2/3/4/5/6 to move active window to specific workspace
    - key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-1"
      value: "['<Super><Shift>1']"
    - key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-2"
      value: "['<Super><Shift>2']"
    - key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-3"
      value: "['<Super><Shift>3']"
    - key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-4"
      value: "['<Super><Shift>4']"
    - key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-5"
      value: "['<Super><Shift>5']"
    - key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-6"
      value: "['<Super><Shift>6']"

    # Super + Shift + / to move active window to next workspace (right)
    - key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-right"
      value: "['<Super><Shift>slash']"

    # Super + Shift + . to move active window to previous workspace (left)
    - key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-left"
      value: "['<Super><Shift>period']"

    # Super + Q to close active window (closest equivalent to "close workspace")
    - key: "/org/gnome/desktop/wm/keybindings/close"
      value: "['<Super>q']"

- name: Ensure dynamic workspaces are enabled (recommended for workspace shortcuts)
  dconf:
    key: "/org/gnome/mutter/dynamic-workspaces"
    value: "true"
    state: present

- name: Set number of static workspaces (if you prefer static workspaces)
  dconf:
    key: "/org/gnome/desktop/wm/preferences/num-workspaces"
    value: "6"
    state: present
  when: false # Set to true if you want static workspaces instead

- name: Disable dynamic workspaces (only if using static workspaces)
  dconf:
    key: "/org/gnome/mutter/dynamic-workspaces"
    value: "false"
    state: present
  when: false
