---
- name: Install window manager packages via yay
  shell: yay -S --noconfirm {{ wm_packages | join(' ') }}
  args:
    executable: /bin/bash
    creates: /usr/bin/i3
  become_user: "{{ ansible_user }}"
