- name: git clone dotfiles
  git:
    repo: https://github.com/2SSK/dot-files.git
    dest: /home/{{ ansible_user }}/dotfiles
    version: main
    force: yes

- name: Install Oh My Zsh
  shell: |
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  args:
    creates: /home/ssk/.oh-my-zsh

- name: stow dotfiles
  shell: |
    cd /home/{{ ansible_user }}/dotfiles && stow .

- name: git clone wallpapers repo
  git:
    repo: https://github.com/2SSK/Wallpaper-bank.git
    dest: /home/{{ ansible_user }}/Wallpaper-bank
    version: main
    force: yes
