---
# Install development packages using the common package manager role
- name: Install development packages
  include_role:
    name: package-manager
  vars:
    package_list: "{{ dev_packages }}"
    snap_package_list: "{{ dev_packages_snap | default([]) }}"
    flatpak_package_list: "{{ dev_packages_flatpak | default([]) }}"
    cargo_package_list: "{{ dev_packages_cargo | default([]) }}"

# Install packages that require manual installation
- name: Install GitHub CLI manually (Debian)
  block:
    - name: Download GitHub CLI
      get_url:
        url: "https://github.com/cli/cli/releases/latest/download/gh_{{ ansible_architecture }}_linux_amd64.deb"
        dest: "/tmp/gh.deb"
      when: ansible_architecture == "x86_64"

    - name: Install GitHub CLI
      apt:
        deb: "/tmp/gh.deb"
        state: present
  when:
    - current_distro == 'debian'
    - "'gh' in (dev_packages_manual | default([]))"

- name: Install Vim-Plug for Vim
  shell: |
    curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  args:
    creates: ~/.vim/autoload/plug.vim
  become_user: "{{ ansible_user }}"

- name: Install Vim plugins via PlugInstall
  shell: |
    vim +PlugInstall +qall
  args:
    executable: /bin/bash
  become_user: "{{ ansible_user }}"

- name: Install TPM (Tmux Plugin Manager)
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: "/home/{{ ansible_user }}/.tmux/plugins/tpm"
  become_user: "{{ ansible_user }}"

- name: Install TPM plugins listed in .tmux.conf
  shell: "/home/{{ ansible_user }}/.tmux/plugins/tpm/bin/install_plugins"
  args:
    executable: /bin/bash
  become_user: "{{ ansible_user }}"

- name: Start and enable Docker service
  systemd:
    name: docker
    enabled: true
    state: started

- name: Add user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true
